---
# tasks file for repo-epel
- name: Install EPEL (CentOS) repo.
  yum: name=epel-release state=present
  when: ansible_distribution == "CentOS"

- name: Install EPEL (RHEL) repo.
  yum: name="{{ epel_repo_url }}" state=present
  when: ansible_distribution == "Red Hat Enterprise Linux"

- name: Import EPEL GPG key.
  rpm_key: key="{{ epel_repo_gpg_key_url }}" state=present
  when: ansible_distribution == "Red Hat Enterprise Linux"
